### ISSUE TITLE
Multiple <p>s in a <blockquote> look bad.

### ISSUE THREAD

**Issue by hjiang** [amsf/amsf-curtana#4]
The vertical quote indicator would break.

![_ _1_byte](https://cloud.githubusercontent.com/assets/18527/11585095/553bc114-9aa4-11e5-9361-85025945ac84.png)

**Comment by sparanoid** [comment]
Currently you need special markup to make it look better:

``` html
<blockquote>
  <p>
    … these mean that in many fields the rule will be: Build it, and they will come.
  </p>

  <footer>
    <cite>Paul Graham</cite>
  </footer>
</blockquote>
```

I'll look for a better solution.
